
server:
  port: 8082

spring:
  application:
    name: service-dream-a

eureka:
  client:
    service-url:
      #填写eureka服务器地址
      defaultZone: http://127.0.0.1:8081/eureka
    #将自己注册到注册中心
    register-with-eureka: true
    fetch-registry: true
  instance:
    #使用ip地址注册到eureka注册中心
    prefer-ip-address: true
    #注册中心显示的状态参数
    instance-id: ${spring.cloud.client.ip-address}:${server.port}